**The following array is given:**



A = np.array([[-4, 3, 0, 1, -5], [6, -4, -2, 1, 3]])


**Use the sign function for this array.**

In [1]:
import numpy as np


A = np.array([[-4, 3, 0, 1, -5], [6, -4, -2, 1, 3]])

In [2]:
np.sign(A)

array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])

In [3]:
print(np.sign(A))

[[-1  1  0  1 -1]
 [ 1 -1 -1  1  1]]
