**The following array is given:**


image = np.random.randint(
    low=0, high=256, size=(200, 300, 3), dtype=np.uint8
)


**Extend this array by one dimension (add a new dimension at the beginning) and assign to image_extended variable. Expected shape of this array is (1, 200, 300, 3).**



In [1]:
import numpy as np


image = np.random.randint(
    low=0, high=256, size=(200, 300, 3), dtype=np.uint8
)

In [6]:
image_extended = (np.expand_dims(image, axis=0))

In [7]:
print(image_extended)

[[[[ 58 243  12]
   [217 160 247]
   [144 202 202]
   ...
   [ 50   9  31]
   [ 12 162 163]
   [157  74   5]]

  [[ 52  60 205]
   [217  74 172]
   [228 189 179]
   ...
   [ 76 192 140]
   [160 228 208]
   [ 26 106 127]]

  [[177  82  71]
   [208 205 214]
   [235  36 143]
   ...
   [  9 254 255]
   [218  23  49]
   [193 168  59]]

  ...

  [[ 62 183  55]
   [ 67 128 204]
   [ 75 202 217]
   ...
   [163 167  44]
   [203 127  88]
   [123 116 178]]

  [[153 189  68]
   [  1  73 103]
   [231 201  60]
   ...
   [173 118  53]
   [151  17 106]
   [184  73  75]]

  [[ 70 186 156]
   [133 173   8]
   [223  29  92]
   ...
   [ 11 133 242]
   [232 207  33]
   [ 12  27  65]]]]
