In [1]:
import numpy as np

In [10]:
A = np.array(
    [
        [[4, 5, 4, 2], [6, 3, 5, 1], [5, 2, 1, 2]],
        [[7, 2, 3, 1], [6, 2, 0, 9], [0, 1, 9, 1]],
    ]
)

In [11]:
A

array([[[4, 5, 4, 2],
        [6, 3, 5, 1],
        [5, 2, 1, 2]],

       [[7, 2, 3, 1],
        [6, 2, 0, 9],
        [0, 1, 9, 1]]])

In [12]:
print(A)

[[[4 5 4 2]
  [6 3 5 1]
  [5 2 1 2]]

 [[7 2 3 1]
  [6 2 0 9]
  [0 1 9 1]]]
