**The following three one-dimensional arrays are given:**



feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])


**Transform each of these arrays into a column and concatenate them into one array**

In [1]:
import numpy as np


feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])

In [4]:
feature1 = np.column_stack(feature1)

In [5]:
feature1

array([[1.6, 0.9, 2.2]])

In [6]:
feature2 = np.column_stack(feature2)

In [7]:
feature3 = np.column_stack(feature3)

In [8]:
feature = np.concatenate((feature1, feature2, feature3), axis=0)

In [9]:
print(feature)

[[1.6 0.9 2.2]
 [0.4 1.3 3.2]
 [1.4 0.3 1.2]]


In [10]:
features = np.column_stack(feature)

In [11]:
features

array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])

In [12]:
print(features)

[[1.6 0.4 1.4]
 [0.9 1.3 0.3]
 [2.2 3.2 1.2]]
