**Using Numpy create the following array:**



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])


**Save this array to a binary file named 'array.npy' and then load that file back into another variable. Print this variable to the console.**



In [1]:
import numpy as np

In [4]:
A = np.arange(12).reshape(-1,4)

In [5]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
np.save('array.npy', A)

In [8]:
np.load('array.npy')

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
B = np.load('array.npy')
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])