**Sort the array in Exercise 39 along the rows in ascending order and assign to the variable image_sorted.**

In [1]:
import numpy as np

In [2]:
image = np.random.randint(0, 255, size=(200,300), dtype=np.uint8)

In [3]:
image

array([[193, 113, 254, ...,  48,   7, 198],
       [147, 112,  74, ...,  12,  88, 128],
       [233,  83, 171, ...,  74, 165, 105],
       ...,
       [197, 103, 231, ..., 231, 204,  68],
       [184, 175, 124, ..., 227, 153, 253],
       [ 56, 124,  83, ..., 221,  10,  42]], dtype=uint8)

In [4]:
print(image)

[[193 113 254 ...  48   7 198]
 [147 112  74 ...  12  88 128]
 [233  83 171 ...  74 165 105]
 ...
 [197 103 231 ... 231 204  68]
 [184 175 124 ... 227 153 253]
 [ 56 124  83 ... 221  10  42]]


In [5]:
np.sort(image)

array([[  0,   1,   3, ..., 254, 254, 254],
       [  0,   1,   1, ..., 253, 254, 254],
       [  1,   1,   1, ..., 252, 252, 254],
       ...,
       [  0,   0,   1, ..., 254, 254, 254],
       [  0,   0,   3, ..., 252, 253, 253],
       [  0,   0,   0, ..., 252, 253, 254]], dtype=uint8)

In [6]:
image_sorted = np.sort(image)