**The following array is given:**



image = np.random.randint(
    low=0, high=256, size=(10, 10, 3), dtype=np.uint8
)


**Extract any array of shape (5, 5, 3) from this array and assign to the result variable.**



In [1]:
import numpy as np


image = np.random.randint(
    low=0, high=256, size=(10, 10, 3), dtype=np.uint8
)

In [2]:
image

array([[[239, 161,   5],
        [113, 233,  77],
        [  7, 106, 105],
        [240, 242, 180],
        [  2,  68, 213],
        [242, 186, 118],
        [199, 169,  88],
        [103, 222, 203],
        [113,  57, 137],
        [132, 134,  69]],

       [[203,  60,  60],
        [106,  60,  50],
        [ 91, 230, 133],
        [174, 223, 141],
        [254, 207, 171],
        [ 53,  61, 164],
        [191, 163,  45],
        [139, 227, 153],
        [136, 116, 147],
        [ 85,  10, 250]],

       [[ 38,  68, 112],
        [164, 182, 139],
        [185, 148, 135],
        [ 36, 216, 129],
        [179, 141, 255],
        [172, 204, 147],
        [ 84, 133, 181],
        [ 74, 100,   3],
        [207, 247, 220],
        [229, 148, 211]],

       [[ 43, 220, 249],
        [253, 237, 140],
        [ 57, 213, 180],
        [150,  43,  69],
        [252,  44,  79],
        [229,  42, 174],
        [122, 102, 222],
        [102,  66, 208],
        [ 18, 158,  59],
        [220, 117, 

In [3]:
image[:5, :5, :]

array([[[239, 161,   5],
        [113, 233,  77],
        [  7, 106, 105],
        [240, 242, 180],
        [  2,  68, 213]],

       [[203,  60,  60],
        [106,  60,  50],
        [ 91, 230, 133],
        [174, 223, 141],
        [254, 207, 171]],

       [[ 38,  68, 112],
        [164, 182, 139],
        [185, 148, 135],
        [ 36, 216, 129],
        [179, 141, 255]],

       [[ 43, 220, 249],
        [253, 237, 140],
        [ 57, 213, 180],
        [150,  43,  69],
        [252,  44,  79]],

       [[181,  23, 229],
        [127, 202,  38],
        [138, 209,  62],
        [240, 216, 204],
        [ 56, 120, 238]]], dtype=uint8)

In [4]:
print(image[:5, :5, :])

[[[239 161   5]
  [113 233  77]
  [  7 106 105]
  [240 242 180]
  [  2  68 213]]

 [[203  60  60]
  [106  60  50]
  [ 91 230 133]
  [174 223 141]
  [254 207 171]]

 [[ 38  68 112]
  [164 182 139]
  [185 148 135]
  [ 36 216 129]
  [179 141 255]]

 [[ 43 220 249]
  [253 237 140]
  [ 57 213 180]
  [150  43  69]
  [252  44  79]]

 [[181  23 229]
  [127 202  38]
  [138 209  62]
  [240 216 204]
  [ 56 120 238]]]
