**The following array is given:**



A = np.array(
    [[4.99, 3.49, 9.99], [1.99, 9.99, 4.99], [14.99, 2.39, 7.29]]
)


**Sort this array:**

    -by row (ascending)

    -by column (ascending)

**And print result to the console.**



In [1]:
import numpy as np

In [2]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

In [3]:
np.sort(A)

array([[ 3.49,  4.99,  9.99],
       [ 1.99,  4.99,  9.99],
       [ 2.39,  7.29, 14.99]])

In [4]:
-np.sort(-A)

array([[ 9.99,  4.99,  3.49],
       [ 9.99,  4.99,  1.99],
       [14.99,  7.29,  2.39]])

In [8]:
A[-A[:,].argsort()]

array([[[14.99,  2.39,  7.29],
        [ 4.99,  3.49,  9.99],
        [ 1.99,  9.99,  4.99]],

       [[ 4.99,  3.49,  9.99],
        [ 1.99,  9.99,  4.99],
        [14.99,  2.39,  7.29]],

       [[14.99,  2.39,  7.29],
        [ 1.99,  9.99,  4.99],
        [ 4.99,  3.49,  9.99]]])

In [11]:
print(np.sort(A))

[[ 3.49  4.99  9.99]
 [ 1.99  4.99  9.99]
 [ 2.39  7.29 14.99]]


In [12]:
print(np.sort(A, axis=0))

[[ 1.99  2.39  4.99]
 [ 4.99  3.49  7.29]
 [14.99  9.99  9.99]]
