**Check if all elements from the following arrays return the logical value True**

In [1]:
import numpy as np

In [3]:
A = np.array([[3, 2, 1, 4],
            [5, 2, 1, 6]])

In [4]:
A

array([[3, 2, 1, 4],
       [5, 2, 1, 6]])

In [5]:
B = np.array([[3,2,1,4],
             [5,2,0,6]])

In [6]:
B

array([[3, 2, 1, 4],
       [5, 2, 0, 6]])

In [7]:
C=np.array([[True, False, False],
         [True, True, True]])

In [8]:
C

array([[ True, False, False],
       [ True,  True,  True]])

In [9]:
D=np.array([0.1, 0.3])

In [10]:
D

array([0.1, 0.3])

- To check if the elements from the arrays return True or False, we will use **np.all()** Function

In [11]:
np.all(A)

True

In [12]:
np.all(B)

False

In [13]:
np.all(C)

False

In [15]:
np.all(D)

True

In [16]:
print("A:",np.all(A))
print("B:",np.all(B))
print("C:",np.all(C))
print("D:",np.all(D))

A: True
B: False
C: False
D: True
