**Using Numpy create a three-dimensional array called image with shape (200, 300, 3) filled with random values from 0 to 255 (inclusive) and data type np.uint8. Set random seed to 42.**

**In response, print array to the console.**

In [5]:
import numpy as np


np.random.seed(42)

In [9]:
image = np.random.randint(low=0, high=256, size=(200,300,3), dtype=np.uint8)

In [10]:
image

array([[[142, 229, 254],
        [254, 165, 235],
        [ 44, 141,  49],
        ...,
        [188, 228, 235],
        [150,  92,  69],
        [141,  53, 255]],

       [[157,  79, 123],
        [148, 231, 178],
        [211, 196, 142],
        ...,
        [228, 164,  10],
        [ 73, 167, 231],
        [137, 138, 113]],

       [[212, 224, 151],
        [120, 156,  39],
        [255, 152, 253],
        ...,
        [127, 248, 216],
        [190, 211,  25],
        [106, 200, 169]],

       ...,

       [[  2, 126, 153],
        [ 71, 203, 115],
        [119,  81, 204],
        ...,
        [164,  24,  85],
        [ 69, 250, 148],
        [ 33, 245,  14]],

       [[121, 248, 201],
        [ 77, 210, 150],
        [191, 196,  87],
        ...,
        [165,  92,  63],
        [231, 207,  30],
        [ 38, 215, 132]],

       [[236,  90, 107],
        [148, 173,  25],
        [ 45,  62, 154],
        ...,
        [ 14, 169,  18],
        [ 82,  87, 224],
        [220, 117,  62]]

In [11]:
print(image)

[[[142 229 254]
  [254 165 235]
  [ 44 141  49]
  ...
  [188 228 235]
  [150  92  69]
  [141  53 255]]

 [[157  79 123]
  [148 231 178]
  [211 196 142]
  ...
  [228 164  10]
  [ 73 167 231]
  [137 138 113]]

 [[212 224 151]
  [120 156  39]
  [255 152 253]
  ...
  [127 248 216]
  [190 211  25]
  [106 200 169]]

 ...

 [[  2 126 153]
  [ 71 203 115]
  [119  81 204]
  ...
  [164  24  85]
  [ 69 250 148]
  [ 33 245  14]]

 [[121 248 201]
  [ 77 210 150]
  [191 196  87]
  ...
  [165  92  63]
  [231 207  30]
  [ 38 215 132]]

 [[236  90 107]
  [148 173  25]
  [ 45  62 154]
  ...
  [ 14 169  18]
  [ 82  87 224]
  [220 117  62]]]
