**Using Numpy create a one-dimensional array (vector) containing the possible result from the Big Lotto game. Set the random seed to 42. Print result to the console.**

In [1]:
import numpy as np

In [6]:
np.random.randn(6)

array([ 0.24196227, -1.91328024, -1.72491783, -0.56228753, -1.01283112,
        0.31424733])

In [10]:
np.random.choice(range(1,50),size=6, replace=False)

array([ 3,  1, 27, 23, 13, 38])

In [11]:
np.random.seed(42)

In [12]:
print(np.random.choice(range(1,50),size=6, replace=False))

[14 46 48 45 18 28]
