**The following arrays are given:**



A = np.array([[3, 4, 5], [8, 3, 1]])
B = np.array([[0, 5, 2], [4, 2, 1]])


**Concatenate these arrays.**

In [1]:
import numpy as np


A = np.array([[3, 4, 5], [8, 3, 1]])
B = np.array([[0, 5, 2], [4, 2, 1]])

In [3]:
print(np.concatenate((A, B)))

[[3 4 5]
 [8 3 1]
 [0 5 2]
 [4 2 1]]
