**The following arrays are given:**



A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')


**Check the Pythagorean formula for sines and cosines on the A array and then compare the result with the B array. Use the np.allclose() function in this exercise.**

**In response, print result to the console.**

In [1]:
import numpy as np


A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')

In [2]:
A

array([0.        , 0.08267349, 0.16534698, 0.24802047, 0.33069396,
       0.41336745, 0.49604095, 0.57871444, 0.66138793, 0.74406142,
       0.82673491, 0.9094084 , 0.99208189, 1.07475538, 1.15742887,
       1.24010236, 1.32277585, 1.40544935, 1.48812284, 1.57079633])

In [3]:
B

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [4]:
np.allclose(A,B)

False

In [5]:
np.sin(A)**2 + np.cos(A)**2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [6]:
np.allclose((np.sin(A)**2 + np.cos(A)**2), B)

True

In [7]:
print(np.allclose((np.sin(A)**2 + np.cos(A)**2), B))

True
