**The following array is given:**



A = np.random.randn(10, 8)


**Round the values of this array to three decimal places and print result to the console.**

In [1]:
import numpy as np


np.random.seed(42)
A = np.random.randn(10, 8)

In [2]:
A

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
        -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975,  0.24196227,
        -1.91328024, -1.72491783, -0.56228753],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ,  1.46564877,
        -0.2257763 ,  0.0675282 , -1.42474819],
       [-0.54438272,  0.11092259, -1.15099358,  0.37569802, -0.60063869,
        -0.29169375, -0.60170661,  1.85227818],
       [-0.01349722, -1.05771093,  0.82254491, -1.22084365,  0.2088636 ,
        -1.95967012, -1.32818605,  0.19686124],
       [ 0.73846658,  0.17136828, -0.11564828, -0.3011037 , -1.47852199,
        -0.71984421, -0.46063877,  1.05712223],
       [ 0.34361829, -1.76304016,  0.32408397, -0.38508228, -0.676922  ,
         0.61167629,  1.03099952,  0.93128012],
       [-0.83921752, -0.30921238,  0.33126343,  0.97554513, -0.47917424,
        -0.18565898, -1.10633497, -1.19620662],
       [ 0.81252582,  1.35624003

In [3]:
np.round(A, decimals=3)

array([[ 0.497, -0.138,  0.648,  1.523, -0.234, -0.234,  1.579,  0.767],
       [-0.469,  0.543, -0.463, -0.466,  0.242, -1.913, -1.725, -0.562],
       [-1.013,  0.314, -0.908, -1.412,  1.466, -0.226,  0.068, -1.425],
       [-0.544,  0.111, -1.151,  0.376, -0.601, -0.292, -0.602,  1.852],
       [-0.013, -1.058,  0.823, -1.221,  0.209, -1.96 , -1.328,  0.197],
       [ 0.738,  0.171, -0.116, -0.301, -1.479, -0.72 , -0.461,  1.057],
       [ 0.344, -1.763,  0.324, -0.385, -0.677,  0.612,  1.031,  0.931],
       [-0.839, -0.309,  0.331,  0.976, -0.479, -0.186, -1.106, -1.196],
       [ 0.813,  1.356, -0.072,  1.004,  0.362, -0.645,  0.361,  1.538],
       [-0.036,  1.565, -2.62 ,  0.822,  0.087, -0.299,  0.092, -1.988]])

In [4]:
print(np.round(A, decimals=3))

[[ 0.497 -0.138  0.648  1.523 -0.234 -0.234  1.579  0.767]
 [-0.469  0.543 -0.463 -0.466  0.242 -1.913 -1.725 -0.562]
 [-1.013  0.314 -0.908 -1.412  1.466 -0.226  0.068 -1.425]
 [-0.544  0.111 -1.151  0.376 -0.601 -0.292 -0.602  1.852]
 [-0.013 -1.058  0.823 -1.221  0.209 -1.96  -1.328  0.197]
 [ 0.738  0.171 -0.116 -0.301 -1.479 -0.72  -0.461  1.057]
 [ 0.344 -1.763  0.324 -0.385 -0.677  0.612  1.031  0.931]
 [-0.839 -0.309  0.331  0.976 -0.479 -0.186 -1.106 -1.196]
 [ 0.813  1.356 -0.072  1.004  0.362 -0.645  0.361  1.538]
 [-0.036  1.565 -2.62   0.822  0.087 -0.299  0.092 -1.988]]
