In [1]:
import numpy as np


A = np.array([[5, 8, 16], [4, 1, 8], [-4, 4, -11]])

In [4]:
eigenvalues, eigenvectors = np.linalg.eig(A)

In [6]:
print(eigenvalues)

[-9.24621125 -3.          7.24621125]


In [7]:
print(eigenvectors)

[[-6.26164716e-01 -8.94427191e-01  8.90159406e-01]
 [-3.13082358e-01  3.52999668e-17  4.45079703e-01]
 [ 7.14070855e-01  4.47213595e-01 -9.75719719e-02]]
