**The following array (square matrix) is given:**



A = np.array([[5, 8, 16], [4, 1, 8], [-4, 4, -11]])


**Find the inverse matrix to this matrix and print it to the console.**

In [1]:
import numpy as np


A = np.array([[5, 8, 16], [4, 1, 8], [-4, 4, -11]])

In [2]:
np.linalg.inv(A)

array([[-0.21393035,  0.75621891,  0.23880597],
       [ 0.05970149,  0.04477612,  0.11940299],
       [ 0.09950249, -0.25870647, -0.13432836]])

In [3]:
print(np.linalg.inv(A))

[[-0.21393035  0.75621891  0.23880597]
 [ 0.05970149  0.04477612  0.11940299]
 [ 0.09950249 -0.25870647 -0.13432836]]
