**The following arrays are given:**



A = np.array([[3, 4, 9, 2], [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5], [6, 3, 1, 6]])


**Multiply these arrays (elementwise) and print result to the console.**

In [1]:
import numpy as np


A = np.array([[3, 4, 9, 2], [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5], [6, 3, 1, 6]])

In [2]:
np.multiply(A,B)

array([[12, 12, 18, 10],
       [30,  9,  2, 30]])

In [3]:
print(np.multiply(A,B))

[[12 12 18 10]
 [30  9  2 30]]
