**The following array is given:**



A = np.random.randn(8, 4)


**Remove the third column and print this array to the console.**

In [1]:
import numpy as np


np.random.seed(42)

A = np.random.randn(8, 4)

In [2]:
A

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783, -0.56228753],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ],
       [ 1.46564877, -0.2257763 ,  0.0675282 , -1.42474819],
       [-0.54438272,  0.11092259, -1.15099358,  0.37569802],
       [-0.60063869, -0.29169375, -0.60170661,  1.85227818]])

In [5]:
np.delete(A, 2, axis=1)

array([[ 0.49671415, -0.1382643 ,  1.52302986],
       [-0.23415337, -0.23413696,  0.76743473],
       [-0.46947439,  0.54256004, -0.46572975],
       [ 0.24196227, -1.91328024, -0.56228753],
       [-1.01283112,  0.31424733, -1.4123037 ],
       [ 1.46564877, -0.2257763 , -1.42474819],
       [-0.54438272,  0.11092259,  0.37569802],
       [-0.60063869, -0.29169375,  1.85227818]])

In [6]:
print(np.delete(A, 2, axis=1))

[[ 0.49671415 -0.1382643   1.52302986]
 [-0.23415337 -0.23413696  0.76743473]
 [-0.46947439  0.54256004 -0.46572975]
 [ 0.24196227 -1.91328024 -0.56228753]
 [-1.01283112  0.31424733 -1.4123037 ]
 [ 1.46564877 -0.2257763  -1.42474819]
 [-0.54438272  0.11092259  0.37569802]
 [-0.60063869 -0.29169375  1.85227818]]
