**Random seed is set to 42. The following array is given:**



image = np.random.randint(
    low=0, high=256, size=(10, 10, 3), dtype=np.uint8
)


**Extract the first channel (index 0) of this image array and print it to the console.**



In [1]:
import numpy as np


np.random.seed(42)

image = np.random.randint(
    low=0, high=256, size=(10, 10, 3), dtype=np.uint8
)


In [2]:
image

array([[[102, 220, 225],
        [ 95, 179,  61],
        [234, 203,  92],
        [  3,  98, 243],
        [ 14, 149, 245],
        [ 46, 106, 244],
        [ 99, 187,  71],
        [212, 153, 199],
        [188, 174,  65],
        [153,  20,  44]],

       [[203, 152, 102],
        [214, 240,  39],
        [121,  24,  34],
        [114, 210,  65],
        [239,  39, 214],
        [244, 151,  25],
        [ 74, 145, 222],
        [ 14, 202,  85],
        [145, 117,  87],
        [184, 189, 221]],

       [[116, 237, 109],
        [ 85,  99, 172],
        [226, 153, 103],
        [235, 146,  36],
        [151,  62,  68],
        [181, 130, 160],
        [160, 166, 149],
        [  6,  69,   5],
        [ 52, 253, 112],
        [ 14,   1,   3]],

       [[ 76, 248,  87],
        [233, 212, 184],
        [235, 245,  26],
        [213, 157, 253],
        [ 68, 240,  37],
        [219,  91,  54],
        [129,   9,  51],
        [  0, 191,  20],
        [140,  46, 187],
        [147,   1, 

In [13]:
image[:, :, 0]

array([[102,  95, 234,   3,  14,  46,  99, 212, 188, 153],
       [203, 214, 121, 114, 239, 244,  74,  14, 145, 184],
       [116,  85, 226, 235, 151, 181, 160,   6,  52,  14],
       [ 76, 233, 235, 213,  68, 219, 129,   0, 140, 147],
       [ 20,  46,  19, 209,  57, 156,  86,  24, 235, 110],
       [231, 254, 218, 134, 162,  73, 169,  35, 242, 253],
       [187, 249, 201, 231, 189, 116,  49,  74, 189, 158],
       [ 29,   7,  54, 131, 181, 123, 248, 119, 228,  13],
       [ 50, 155,  40, 120,  72, 115, 167,  85, 131, 242],
       [ 52, 169,  13, 144, 243, 167,   8,  77,  22,  10]], dtype=uint8)

In [14]:
print(image[:, :, 0])

[[102  95 234   3  14  46  99 212 188 153]
 [203 214 121 114 239 244  74  14 145 184]
 [116  85 226 235 151 181 160   6  52  14]
 [ 76 233 235 213  68 219 129   0 140 147]
 [ 20  46  19 209  57 156  86  24 235 110]
 [231 254 218 134 162  73 169  35 242 253]
 [187 249 201 231 189 116  49  74 189 158]
 [ 29   7  54 131 181 123 248 119 228  13]
 [ 50 155  40 120  72 115 167  85 131 242]
 [ 52 169  13 144 243 167   8  77  22  10]]
