**Present the following two-dimensional array as a flattened one-dimensional array and print result to the console.**



A = np.array(
    [
        [4.99, 3.49, 9.99],
        [1.99, 9.99, 14.99],
        [14.99, 2.39, 7.29],
    ]
)


In [1]:
import numpy as np


A = np.array(
    [
        [4.99, 3.49, 9.99],
        [1.99, 9.99, 14.99],
        [14.99, 2.39, 7.29],
    ]
)


In [2]:
A

array([[ 4.99,  3.49,  9.99],
       [ 1.99,  9.99, 14.99],
       [14.99,  2.39,  7.29]])

In [3]:
np.ravel(A)

array([ 4.99,  3.49,  9.99,  1.99,  9.99, 14.99, 14.99,  2.39,  7.29])

In [4]:
print(np.ravel(A))

[ 4.99  3.49  9.99  1.99  9.99 14.99 14.99  2.39  7.29]
