**The following array is given:**



A = np.array(
    [
        [4.99, 3.49, 9.99],
        [1.99, 9.99, 14.99],
        [14.99, 2.39, 7.29],
    ]
)


**Replace elements greater than 10 with a fixed value = 10.0 and print result to the console.**



In [1]:
import numpy as np


A = np.array(
    [
        [4.99, 3.49, 9.99],
        [1.99, 9.99, 14.99],
        [14.99, 2.39, 7.29],
    ]
)


In [2]:
A

array([[ 4.99,  3.49,  9.99],
       [ 1.99,  9.99, 14.99],
       [14.99,  2.39,  7.29]])

In [4]:
np.where(A < 10, A, 10.0)

array([[ 4.99,  3.49,  9.99],
       [ 1.99,  9.99, 10.  ],
       [10.  ,  2.39,  7.29]])

In [5]:
print(np.where(A < 10, A, 10.0))

[[ 4.99  3.49  9.99]
 [ 1.99  9.99 10.  ]
 [10.    2.39  7.29]]
