**Check if all elements from the following arrays return the logical value True along the axis with index 1**

In [2]:
import numpy as np

In [3]:
A = np.array([[3, 2, 1, 4],
            [5, 2, 1, 6]])

In [4]:
A

array([[3, 2, 1, 4],
       [5, 2, 1, 6]])

In [5]:
B = np.array([[3,2,1,4],
             [5,2,0,6]])

In [6]:
B

array([[3, 2, 1, 4],
       [5, 2, 0, 6]])

In [7]:
C=np.array([[True, False, False],
         [True, True, True]])

In [8]:
C

array([[ True, False, False],
       [ True,  True,  True]])

In [9]:
D=np.array([0.1, 0.3])

In [10]:
D

array([0.1, 0.3])

- To check if the elements from the arrays return True or False, we will use **np.all()** Function

In [11]:
np.all(A, axis=1)

array([ True,  True])

In [12]:
np.all(B, axis=1)

array([ True, False])

In [13]:
np.all(C, axis=1)

array([False,  True])

In [14]:
np.all(D,axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [17]:
for name, array in zip(list('ABC'), [A, B, C]):
    print(f'{name}: {np.all(array, axis=1)}')

A: [ True  True]
B: [ True False]
C: [False  True]
