**Two randomly generated arrays are given:**



image1 = np.random.randint(
    low=0, high=256, size=(200, 300, 3), dtype=np.uint8
)
image2 = np.random.randint(
    low=0, high=256, size=(200, 300, 3), dtype=np.uint8
)


**Expand each of these arrays by adding one dimension at the beginning and then combine these arrays into one called images. Expected shape of images array: (2, 200, 300, 3).**

In [1]:
import numpy as np


image1 = np.random.randint(
    low=0, high=256, size=(200, 300, 3), dtype=np.uint8
)
image2 = np.random.randint(
    low=0, high=256, size=(200, 300, 3), dtype=np.uint8
)


In [2]:
image1

array([[[206,  46,  87],
        [ 16, 129, 155],
        [  3, 118,  49],
        ...,
        [ 62,  74,  37],
        [ 58, 144,  36],
        [108,  88, 147]],

       [[251, 184, 196],
        [210,  57, 132],
        [110, 208,  26],
        ...,
        [226, 220,  46],
        [228, 177,  27],
        [ 60,   1,  50]],

       [[ 25, 148, 135],
        [133, 242, 216],
        [136,  28, 179],
        ...,
        [ 94,  81, 100],
        [ 68, 142, 232],
        [233, 102,  56]],

       ...,

       [[ 44,  65,  61],
        [200, 162, 150],
        [ 72, 216, 122],
        ...,
        [150,  23, 203],
        [255,  84,  21],
        [ 64,  53, 198]],

       [[ 39, 199, 185],
        [235,  16, 104],
        [137,  44, 120],
        ...,
        [ 18, 102,  56],
        [250,  34,  79],
        [240, 229, 198]],

       [[205, 156, 150],
        [ 95,  61, 105],
        [251, 155,  27],
        ...,
        [ 79, 113, 158],
        [224,  95,  13],
        [225, 108, 124]]

In [3]:
image2

array([[[ 41,   2, 231],
        [195,  63,  14],
        [106, 204,   0],
        ...,
        [  5,  91, 235],
        [165,  88, 111],
        [225, 207, 193]],

       [[172,  53, 169],
        [  7,  51,  37],
        [ 63, 254,  47],
        ...,
        [155, 255,  51],
        [201, 151, 101],
        [158, 208, 180]],

       [[214, 157, 250],
        [108,  41, 246],
        [235, 223, 230],
        ...,
        [137, 235, 220],
        [ 18,  23,  61],
        [  6,  27,  76]],

       ...,

       [[118, 128, 136],
        [144,  26, 123],
        [ 77,  21,  48],
        ...,
        [ 29, 220,  56],
        [134,  74,  95],
        [  2, 185,  72]],

       [[ 77, 238, 144],
        [180, 183, 180],
        [200, 165, 201],
        ...,
        [ 73, 179,  67],
        [128,  81, 140],
        [221,  17,  86]],

       [[113, 223,  89],
        [219, 230,  45],
        [165,   7,  47],
        ...,
        [ 81, 135, 237],
        [ 61,  48, 214],
        [190,  60, 191]]

In [10]:
images = np.concatenate((image1, image2), axis=1)

In [11]:
images.shape

(200, 600, 3)

In [12]:
im1=np.expand_dims(image1, axis=0)

In [13]:
im1.shape

(1, 200, 300, 3)

In [14]:
im2=np.expand_dims(image2, axis=0)

In [15]:
im2.shape

(1, 200, 300, 3)

In [16]:
im = np.concatenate((im1, im2), axis=0)

In [17]:
im.shape

(2, 200, 300, 3)

In [18]:
print(im)

[[[[206  46  87]
   [ 16 129 155]
   [  3 118  49]
   ...
   [ 62  74  37]
   [ 58 144  36]
   [108  88 147]]

  [[251 184 196]
   [210  57 132]
   [110 208  26]
   ...
   [226 220  46]
   [228 177  27]
   [ 60   1  50]]

  [[ 25 148 135]
   [133 242 216]
   [136  28 179]
   ...
   [ 94  81 100]
   [ 68 142 232]
   [233 102  56]]

  ...

  [[ 44  65  61]
   [200 162 150]
   [ 72 216 122]
   ...
   [150  23 203]
   [255  84  21]
   [ 64  53 198]]

  [[ 39 199 185]
   [235  16 104]
   [137  44 120]
   ...
   [ 18 102  56]
   [250  34  79]
   [240 229 198]]

  [[205 156 150]
   [ 95  61 105]
   [251 155  27]
   ...
   [ 79 113 158]
   [224  95  13]
   [225 108 124]]]


 [[[ 41   2 231]
   [195  63  14]
   [106 204   0]
   ...
   [  5  91 235]
   [165  88 111]
   [225 207 193]]

  [[172  53 169]
   [  7  51  37]
   [ 63 254  47]
   ...
   [155 255  51]
   [201 151 101]
   [158 208 180]]

  [[214 157 250]
   [108  41 246]
   [235 223 230]
   ...
   [137 235 220]
   [ 18  23  61]
   [  6  27