**Using Numpy create the following array:**



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])


**Save this array to a text file named 'array.txt' with two decimal places and then load this file back into another variable. Print this variable to the console.**



In [1]:
import numpy as np

In [21]:
A = np.arange(12, dtype='int').reshape(-1,4)

In [22]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
np.savetxt('array.txt', A, fmt='%0.2f')

In [24]:
B = np.loadtxt('array.txt')

In [25]:
print(B)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
