**The following array is given:**



A = np.array([[4, 2, 1],
              [6, 4, 2]])


**Expand this array by one dimension (add a new dimension at the beginning). Expected shape of the output array: (1, 2, 3).**

**In response, print array to the console.**

In [1]:
import numpy as np


A = np.array([[4, 2, 1],
              [6, 4, 2]])

In [8]:
print(A)

[[4 2 1]
 [6 4 2]]


In [3]:
np.expand_dims(A, axis=(1,2,3))

array([[[[[4, 2, 1]]]],



       [[[[6, 4, 2]]]]])

In [6]:
print(np.expand_dims(A, axis=(0)))

[[[4 2 1]
  [6 4 2]]]
