**Using Numpy create a two-dimensional array with the shape (10, 4) pseudo-randomly generated values from the normal distribution N(100, 5). Set the random seed to 30.**

In [1]:
import numpy as np

- For normal distribution of **N(100,5)**. The **square root** of 5 is 2.236 (variance).

In [2]:
100 + 2.24*np.random.randn(10,4)

array([[101.57939702,  98.90363288, 103.45898103, 101.11904871],
       [102.33050628, 101.80423919,  95.85373432, 100.74198171],
       [101.40795204,  99.79148874,  99.52566862, 100.4672381 ],
       [ 98.12731145, 103.18806266,  97.66536503,  98.6733486 ],
       [104.31592711, 102.00047353,  98.34676853, 100.23600188],
       [100.91522997,  99.7901297 , 100.71920865, 100.817115  ],
       [103.15614322, 100.74646211, 103.48756755,  98.59092356],
       [102.52836722,  96.95572214,  98.3668065 ,  99.61942006],
       [ 99.48162344, 100.54887228, 101.74541791,  97.02489758],
       [101.91488131, 100.70906709,  96.02125614, 100.26521307]])

In [8]:
np.random.seed(30)

In [9]:
print(100 + 2.236*np.random.randn(10,4))

[[ 97.17357824 103.41639637  97.82949034 101.0521713 ]
 [ 99.77484214 100.67928156  96.14074801 103.54427325]
 [100.30028718  97.52507118 103.52891233 100.2403654 ]
 [ 98.29158906  98.26667849 103.09428226 101.70022105]
 [ 99.36129663 101.20378968  95.34040713 102.0968799 ]
 [ 99.9870804   98.95471703  99.05413779 102.38018196]
 [ 93.50807005 103.61536688 103.1874401   98.51360755]
 [102.20249993  96.19775967  97.54007845  97.05821981]
 [101.81228004  97.66387556  98.45888312  98.09323565]
 [102.48972363  95.70426451  98.43166419 101.89856043]]


In [10]:
sigma = np.sqrt(5)

In [12]:
mu = 100

In [13]:
np.random.seed(30)

In [14]:
print(sigma * np.random.randn(10,4) + mu)

[[ 97.17349231 103.41650023  97.82942436 101.05220329]
 [ 99.7748353  100.67930221  96.14063068 103.544381  ]
 [100.30029631  97.52499594 103.52901961 100.24037271]
 [ 98.29153712  98.2666258  103.09437633 101.70027274]
 [ 99.36127721 101.20382627  95.34026547 102.09694365]
 [ 99.98708001  98.95468525  99.05410904 102.38025432]
 [ 93.50787269 103.61547679 103.18753701  98.51356237]
 [102.20256689  96.19764407  97.54000366  97.05813038]
 [101.81233513  97.66380453  98.45883627  98.09317768]
 [102.48979932  95.70413391  98.43161651 101.89861815]]
