**Using Numpy create a 4x4 array filled with zeros (set data type to int). In response print this array to the console.**

In [1]:
import numpy as np

In [2]:
np.zeros((4,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [4]:
print(np.zeros((4,4), dtype='int'))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
