**Using Numpy create a two-dimensional array with shape of (200, 300) filled with random values from 0 to 255 (inclusive) with data type np.uint8 and assign to the variable image.**

In [1]:
import numpy as np

In [5]:
image = np.random.randint(0, 255, size=(200,300), dtype=np.uint8)

In [6]:
image

array([[123,  70, 146, ..., 202, 168,   7],
       [171, 142, 196, ..., 134,  27, 200],
       [119, 221,  75, ..., 167,  36,   8],
       ...,
       [148, 160, 147, ...,  50, 101, 103],
       [ 92, 124, 123, ...,  40, 170, 106],
       [114, 139, 164, ..., 116, 237,  21]], dtype=uint8)

In [7]:
print(image)

[[123  70 146 ... 202 168   7]
 [171 142 196 ... 134  27 200]
 [119 221  75 ... 167  36   8]
 ...
 [148 160 147 ...  50 101 103]
 [ 92 124 123 ...  40 170 106]
 [114 139 164 ... 116 237  21]]
