**Extract all elements from the following array with a value greater than 8 and print result to the console.**



A = np.array(
    [[4.99, 3.49, 9.99], [1.99, 9.99, 4.99], [14.99, 2.39, 7.29]]
)

In [1]:
import numpy as np


A = np.array(
    [[4.99, 3.49, 9.99], [1.99, 9.99, 4.99], [14.99, 2.39, 7.29]]
)

In [2]:
A

array([[ 4.99,  3.49,  9.99],
       [ 1.99,  9.99,  4.99],
       [14.99,  2.39,  7.29]])

In [4]:
A > 8

array([[False, False,  True],
       [False,  True, False],
       [ True, False, False]])

In [6]:
print(A[A>8])

[ 9.99  9.99 14.99]
