**The following arrays are given:**



A = np.array([[3, 4, 9, 2], [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5], [6, 3, 1, 6]])


**Calculate arithmetic means of these arrays (elementwise) and print result to the console.**

In [1]:
import numpy as np


A = np.array([[3, 4, 9, 2], [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5], [6, 3, 1, 6]])

In [5]:
np.mean((A, B), axis=0)

array([[3.5, 3.5, 5.5, 3.5],
       [5.5, 3. , 1.5, 5.5]])

In [6]:
print(np.mean((A,B), axis=0))

[[3.5 3.5 5.5 3.5]
 [5.5 3.  1.5 5.5]]
