**The following arrays are given:**



A = np.array([[2, 3], [-4, 2], [5, 0]])

B = np.array([[4, 3, 2], [-1, 0, 2]])


**Shapes of these arrays:**

A - 3x2

B - 2x3

**Perform matrix multiplication A x B and print result to the console.**

In [1]:
import numpy as np


A = np.array([[2, 3], [-4, 2], [5, 0]])
B = np.array([[4, 3, 2], [-1, 0, 2]])

In [2]:
np.dot(A,B)

array([[  5,   6,  10],
       [-18, -12,  -4],
       [ 20,  15,  10]])

In [3]:
print(np.dot(A,B))

[[  5   6  10]
 [-18 -12  -4]
 [ 20  15  10]]
