**The following array is given:**



A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])


**Return a list of indexes with maximum values for each row from this array and print it to the console.**

In [1]:
import numpy as np

In [2]:
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])

In [3]:
A

array([[0.4, 0.3, 0.3],
       [0.1, 0.1, 0.8],
       [0.2, 0.5, 0.3]])

In [5]:
np.argmax(A, axis=0)

array([0, 2, 1], dtype=int64)

In [6]:
print(np.argmax(A, axis=0))

[0 2 1]
