**The following array is given:**



array(
    [
        [ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]
    ]
)


**Using the slice operator, transform this array into the following:**



array(
    [
        [ 3,  2,  1,  0],
        [ 7,  6,  5,  4],
        [11, 10,  9,  8]
    ]
)

In [1]:
import numpy as np


A = np.arange(12, dtype='int').reshape(-1, 4)

In [2]:
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
print(A[::-1])

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [10]:
print(A[::])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
print(np.flip(A))

[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [13]:
np.flip(A, axis=1)

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])

In [14]:
A[:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
A[:, ::-1]

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])