In [1]:
import numpy as np

In [4]:
W = np.array([0, 4, 5, 1])
Q = np.array([2, 4, -5, 1])

In [5]:
W + Q

array([2, 8, 0, 2])

In [6]:
W - Q

array([-2,  0, 10,  0])

In [7]:
W*Q

array([  0,  16, -25,   1])

In [8]:
W + 2*Q

array([ 4, 12, -5,  3])

In [10]:
print(W+Q)
print(W-Q)
print(W*Q)
print(W+2*Q)

[2 8 0 2]
[-2  0 10  0]
[  0  16 -25   1]
[ 4 12 -5  3]


In [11]:
print(np.polyadd(W,Q))
print(np.polysub(W,Q))
print(np.polymul(W,Q))
print(np.polyadd(W, 2*Q))

[2 8 0 2]
[-2  0 10  0]
[  8  26   2 -17   0   1]
[ 4 12 -5  3]
