**The following arrays are given:**



A = np.array([[2, 0], [4, 2], [5, 3], [4, 2]])

B = np.array([[4, 0, 2, 1, 1, 0, 2, 9]])


**Shapes of these arrays:**

A - 4x2

B - 1x8

**Transform B array to perform the matrix multiplication A x B. Then perform this multiplication and print result to the console.**

In [1]:
import numpy as np


A = np.array([[2, 0], [4, 2], [5, 3], [4, 2]])
B = np.array([[4, 0, 2, 1, 1, 0, 2, 9]])


In [2]:
B = B.reshape(2,-1)

In [3]:
B

array([[4, 0, 2, 1],
       [1, 0, 2, 9]])

In [4]:
np.dot(A, B)

array([[ 8,  0,  4,  2],
       [18,  0, 12, 22],
       [23,  0, 16, 32],
       [18,  0, 12, 22]])

In [5]:
print(np.dot(A, B))

[[ 8  0  4  2]
 [18  0 12 22]
 [23  0 16 32]
 [18  0 12 22]]
