**The following array is given:**



A = np.array([[5, 1, 2, 1, 2],
              [9, 1, 9, 7, 5],
              [4, 1, 5, 7, 9]])


**Extract all unique values of this array as a list and print it to the console**

In [1]:
import numpy as np

In [2]:
A = np.array([[5, 1, 2, 1, 2],
              [9, 1, 9, 7, 5],
              [4, 1, 5, 7, 9]])

In [10]:
A

array([[5, 1, 2, 1, 2],
       [9, 1, 9, 7, 5],
       [4, 1, 5, 7, 9]])

- Another way of inputting the same array:

In [8]:
np.random.seed(10)
B = np.random.randint(low=1, high=10, size=(3, 5))

In [9]:
B

array([[5, 1, 2, 1, 2],
       [9, 1, 9, 7, 5],
       [4, 1, 5, 7, 9]])

In [4]:
np.unique(A)

array([1, 2, 4, 5, 7, 9])

In [5]:
print(np.unique(A))

[1 2 4 5 7 9]
