**Using Numpy create the following two-dimensional array:**

[[0 0 0 0 0 0]
 
 [0 1 0 0 0 0]
 
 [0 0 2 0 0 0]
 
 [0 0 0 3 0 0]
 
 [0 0 0 0 4 0]
 
 [0 0 0 0 0 5]]

In [1]:
import numpy as np

In [4]:
a = np.arange(6)

In [5]:
a

array([0, 1, 2, 3, 4, 5])

In [6]:
np.diag(a)

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])

In [7]:
print(np.diag(a))

[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]
