**The following array is given:**



A = np.random.randint(10, size=(100, 30))


**Set the Numpy option to print only ten edge elements and then print this array to the console.**

In [1]:
import numpy as np


np.random.seed(42)
A = np.random.randint(10, size=(100, 30))

In [2]:
A

array([[6, 3, 7, ..., 2, 6, 3],
       [8, 2, 4, ..., 5, 5, 9],
       [3, 5, 1, ..., 0, 7, 2],
       ...,
       [3, 0, 9, ..., 7, 7, 4],
       [0, 9, 6, ..., 6, 1, 8],
       [9, 1, 2, ..., 0, 8, 6]])

In [3]:
np.set_printoptions(edgeitems=10)

In [4]:
print(A)

[[6 3 7 4 6 9 2 6 7 4 ... 4 0 9 5 8 0 9 2 6 3]
 [8 2 4 2 6 4 8 6 1 3 ... 2 0 3 1 7 3 1 5 5 9]
 [3 5 1 9 1 9 3 7 6 8 ... 6 8 7 0 7 7 2 0 7 2]
 [2 0 4 9 6 9 8 6 8 7 ... 0 2 4 2 0 4 9 6 6 8]
 [9 9 2 6 0 3 3 4 6 6 ... 9 6 8 6 0 0 8 8 3 8]
 [2 6 5 7 8 4 0 2 9 7 ... 2 0 4 0 7 0 0 1 1 5]
 [6 4 0 0 2 1 4 9 5 6 ... 5 0 8 5 2 3 3 2 9 2]
 [2 3 6 3 8 0 7 6 1 7 ... 3 0 1 0 4 4 6 8 8 2]
 [2 2 3 7 5 7 0 7 3 0 ... 1 1 5 2 8 3 0 3 0 4]
 [3 7 7 6 2 0 0 2 5 6 ... 4 2 3 2 0 0 4 5 2 8]
 ...
 [6 4 8 2 0 3 8 3 1 9 ... 8 4 7 1 5 2 9 4 7 9]
 [0 4 2 3 1 8 2 1 9 8 ... 7 7 6 5 8 3 0 7 6 6]
 [2 3 9 8 5 4 2 8 4 4 ... 6 1 7 5 3 4 7 2 2 3]
 [0 8 7 7 9 5 6 5 8 2 ... 2 3 7 5 4 3 7 0 8 0]
 [7 3 8 4 2 8 8 3 3 7 ... 4 4 3 4 2 0 4 8 8 3]
 [2 0 1 7 0 7 6 7 5 8 ... 2 3 6 6 3 5 2 5 1 7]
 [1 6 8 0 7 6 5 5 5 8 ... 2 7 2 3 7 0 5 0 0 7]
 [3 0 9 6 4 4 0 9 5 8 ... 6 8 6 2 0 7 2 7 7 4]
 [0 9 6 9 4 7 8 6 6 0 ... 7 3 0 0 9 2 8 6 1 8]
 [9 1 2 9 1 2 5 8 8 6 ... 8 2 0 6 9 4 4 0 8 6]]
