**Calculate the roots of the following polynomials:**

Q = 2x^3 + 4x^2 - 5x + 1

R = 2x^3 - 5x + 1

**In response print these roots to the console as shown below.**

In [1]:
import numpy as np

In [2]:
Q = np.array([2, 4, -5, 1])

In [4]:
R = np.array([2, 0, -5, 1])

In [5]:
np.roots(Q)

array([-2.91610583,  0.65388685,  0.26221898])

In [6]:
np.roots(R)

array([-1.67298165,  1.46961743,  0.20336421])

In [7]:
print(np.roots(Q))
print(np.roots(R))

[-2.91610583  0.65388685  0.26221898]
[-1.67298165  1.46961743  0.20336421]


In [8]:
S = np.array([2, -5, 1])
np.roots(S)

array([2.28077641, 0.21922359])