In [1]:
import numpy as np


np.random.seed(42)

A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1

In [2]:
A

array([[0, 0, 4, 6, 2, 4, 1, 1],
       [0, 0, 6, 2, 2, 4, 1, 1],
       [0, 0, 1, 3, 5, 5, 1, 1],
       [0, 0, 3, 1, 5, 4, 1, 1],
       [0, 0, 2, 6, 1, 3, 1, 1]])

In [9]:
A1, A2, A3=np.split(A, [2,6], axis=1)

In [10]:
print(A1)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [11]:
print(A2)

[[4 6 2 4]
 [6 2 2 4]
 [1 3 5 5]
 [3 1 5 4]
 [2 6 1 3]]


In [12]:
print(A3)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
