**The following arrays are given:**



A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])      


**Extract the same elements (intersection) of the arrays as a list and print result to the console.**

In [1]:
import numpy as np

In [2]:
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])

In [3]:
A

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [4]:
B

array([[ 9, 10, 11,  3],
       [ 2,  8,  0,  9]])

In [6]:
np.intersect1d(A, B)

array([0, 2, 3])

In [7]:
print(np.intersect1d(A, B))

[0 2 3]
